;; (setq tex-compile-commands '(("xelatex %r")))
;; (setq tex-command "xelatex")
;; (setq-default TeX-engine 'xelatex)

(add-hook 'LaTeX-mode-hook (lambda()
                             (add-to-list 'TeX-command-list '("XeLaTeX" "%`xelatex%(mode)%' %t" TeX-run-TeX nil t))
                             (setq TeX-command-default "XeLaTeX")
                             (setq TeX-save-query  nil )
                             (setq TeX-show-compilation t)
                             ))
